yarnPath: .yarn/releases/yarn-3.6.1.cjs
httpTimeout: 500000

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

# httpsProxy: "http://127.0.0.1:1081"
# httpProxy: "http://127.0.0.1:1081"

progressBarStyle: default
enableGlobalCache: true
